pets:
  cat:
    breeds:
      - Black Domestic Shorthair​
      - Brown Tabby Domestic Shorthair​
      - Gray Domestic Shorthair​
      - Orange Domestic Shorthair​
      - Tuxedo Domestic Shorthair​
      - Calico Domestic Shorthair​
      - Tortoiseshell Domestic Shorthair​
      - Black Domestic Longhair​
      - Brown Tabby Domestic Longhair​
      - Gray Domestic Longhair​
      - Orange Domestic Longhair​
      - Tuxedo Domestic Longhair​
      - Calico Domestic Longhair​
      - Tortoiseshell Domestic Longhair​
      - Seal Point Siamese​
      - Blue Point Siamese​
      - Brown Tabby Maine Coon​
      - Black Maine Coon​
      - White Persian​
      - Black Persian
    temperaments:
      - Friendly
      - Aggressive
      - Calm
      - Curious
      - Playful
      - Shy
      - Affectionate
    max_age: 20
